# Generated by Django 4.1.1 on 2022-09-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_alter_food_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="type_food",
            field=models.CharField(
                choices=[
                    ("B", "صبحانه"),
                    ("D", "نوشیدنی"),
                    ("Di", "شام"),
                    ("L", "نهار"),
                ],
                default="d",
                max_length=10,
                verbose_name="نوع غذا",
            ),
        ),
    ]
