# Generated by Django 4.1.1 on 2022-09-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0003_food_type_food"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="type_food",
            field=models.CharField(
                choices=[
                    ("B", "صبحانه"),
                    ("D", "نوشیدنی"),
                    ("Di", "شام"),
                    ("L", "نهار"),
                ],
                default="di",
                max_length=10,
                verbose_name="نوع غذا",
            ),
        ),
    ]
