# Generated by Django 4.1.1 on 2022-09-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0004_alter_food_type_food"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="type_food",
            field=models.CharField(
                choices=[
                    ("breekfast", "صبحانه"),
                    ("drinks", "نوشیدنی"),
                    ("dinner", "شام"),
                    ("lunch", "نهار"),
                ],
                default="drinks",
                max_length=10,
                verbose_name="نوع غذا",
            ),
        ),
    ]
