# Generated by Django 4.1.1 on 2022-09-11 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="عنوان")),
                (
                    "description",
                    models.CharField(max_length=254, verbose_name="توضیحات"),
                ),
                ("content", models.TextField(verbose_name="محتوا")),
                (
                    "created_ad",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blogs/", verbose_name="تصویر"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=128, verbose_name="عنوان دسته بندی"),
                ),
                ("slug", models.SlugField(verbose_name="عنوان لاتین")),
                (
                    "published",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ انتشار"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="عنوان")),
                ("slug", models.CharField(max_length=128, verbose_name="عنوان لاتین")),
                (
                    "published",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ اپدیت"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="نام")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="پست الکترونیکی"),
                ),
                ("message", models.TextField(verbose_name="متن پیام")),
                (
                    "time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ و زمان"
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blog",
                        verbose_name="مقاله",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="blog.category",
                verbose_name="دسته بندی",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(
                related_name="blogs", to="blog.tag", verbose_name="تگ ها"
            ),
        ),
    ]
