# Generated by Django 4.1.1 on 2022-09-12 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_delete_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="نام")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="پست الکترونیکی"),
                ),
                ("message", models.TextField(verbose_name="متن نظر")),
                (
                    "time",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان انتشار"),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blog",
                        verbose_name="مقاله",
                    ),
                ),
            ],
        ),
    ]
