# Generated by Django 4.1.1 on 2022-09-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="آدرس الکترونیکی"),
                ),
                ("phone", models.CharField(max_length=128, verbose_name="تلفن")),
                ("number", models.IntegerField(verbose_name="تعداد")),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("time", models.TimeField(verbose_name="ساعت")),
            ],
        ),
    ]
